<?
$PERM["bitrix"]["8"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["2"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["3"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["4"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["8"]="R";
$PERM["lichnyy-kabinet-prodavtsa"]["6"]="D";
$PERM["lichnyy-kabinet-prodavtsa"]["7"]="X";
$PERM["lichnyy-kabinet-prodavtsa"]["5"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["2"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["3"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["4"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["8"]="R";
$PERM["lichnyy-kabinet-pokupatelya"]["6"]="X";
$PERM["lichnyy-kabinet-pokupatelya"]["7"]="D";
$PERM["lichnyy-kabinet-pokupatelya"]["5"]="D";
$PERM["obyavleniya"]["8"]="W";
$PERM["login"]["8"]="D";
$PERM["/"]["8"]="D";
$PERM["/"]["*"]="R";
$PERM["search"]["5"]="W";
$PERM["products"]["5"]="W";
$PERM["services"]["5"]="W";
$PERM["news"]["5"]="W";
$PERM["company"]["5"]="W";
$PERM["index.php"]["5"]="W";
?>